site_name: Triagil

repo_name: 'GitHub Repository'
repo_url: 'https://github.com/UnBArqDsw/2020.1_G1_Triagil'

copyright: 'Copyright &copy; 2020 UnB Gama - FGA'

theme:
  name: material
  language: 'pt'
  logo: 'images/icon-white.png'
  favicon: 'images/icon-color-favicon.ico'
  palette:
    primary: 'light blue'
    accent: 'red'
  font:
    text: 'Roboto'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences    

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Início: index.md
  - Base:
    - Design Sprint: base/design_sprint/ds.md
    - Requisitos:
      - Pré-Rastriabilidade:
        - 5W2H: base/requisitos/pre-rastriabilidade/5w2h.md
        - Rich Picture: base/requisitos/pre-rastriabilidade/rp.md
        - Causa-Efeito: base/requisitos/pre-rastriabilidade/causa_e_efeito.md
        - Mapa Mental: base/requisitos/pre-rastriabilidade/mapa_mental.md
      - Elicitação:
        - Brainstorming: base/requisitos/elicitacao/brainstorming.md
        - Entrevista: base/requisitos/elicitacao/entrevista.md
        - Questionário: base/requisitos/elicitacao/questionario.md
        - Storyboard: base/requisitos/elicitacao/storyboard.md
      - Priorização:
        - First Thing First: base/requisitos/priorizacao/first_thing_first.md
        - MoSCoW: base/requisitos/priorizacao/moscow.md    
      - Modelagem:
        - Léxicos: base/requisitos/modelagem/lexico.md
        - Glossário: base/requisitos/modelagem/glossario.md
        # - Backlog do Produto: base/requisitos/modelagem/backlog.md
      - Protótipo de Alta Fidelidade: base/requisitos/prototipo/prototipo_de_alta.md
    - Plano de Custos e Esforços: base/documentos/plano_custos.md
    - Plano de Riscos: base/documentos/plano_risco.md    
    - Apresentação:
      - Metodologias:
        - Scrum: base/apresentacao/metodologia/scrum.md
        - Programação Extrema(XP): base/apresentacao/metodologia/xp.md
    - Modelagem BPMN: base/modelagem_bpmn/bpmn.md
  - Modelagem:
    - UML – Diagramas Estáticos: modelagem/diagramas/uml_estatico.md
    - UML – Diagramas Dinâmicos: modelagem/diagramas/uml_dinamico.md
    - Iniciativa Extra:
      - Backlog do Produto: modelagem/extra/backlog.md
